sudo: required
dist: trusty
language: node_js

node_js:
- '6.9.1'
- 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8
  firefox: 'latest-esr'

env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-default
  global:
    - CXX=g++-4.8
    - secure: DCaFlg71rn/5GdXboHfo+S56aq1xQD1DprovtzoUVqWhEC+88+9X5PRAn3rj+2IVewIUmUXwsMonRAJhj7GWGcFBj/277qiPbOKDJZCBWZcMEWkCRy+KZAXAqJYbg6MEGmSnuuCjJ0n0MDp2nClaQBSvRfuVvGqTWvG//YEnXzLpj3KlsIlBQXCGFLiHWExGT2iMFWCb+O+kPEN8Kw/PP/c3F00LaBH4n1azx2h0Wq2Gv5L2BiWj37lFroIXrKrwSmjHQwsgafSJbqHaamCe9L9VcYg2+8hFbi2ijpmn4a2/YpJmUcnbhFsEHcl3SjARNQ3AvlS6+7+E3iF6LYHBxsJ6Ai5/STDmDTTy3BsH4fu6YY8i0oeJv/kFJl78pT+lCwwtTdFhok3Zp1d6MyWZVwk1DouhYn1lGVPNjalFvJ0TvnJ3ldouUX1vbl5cHl5CfHioVSJheDv8+zY2KA6gd1QeqfQHTLuz8BqcO8zlgvpmVSLi0B1mE1euxlK0w4befnor3T3QvsZZEM6jBkcedNi4Jx1jWwsprWVVVuG/+M+PvAXyBEuzd6/QNKSn/z3GURZ8z5SG3Ytsa9pjvXtgIZa+owGw97THLQCQUSbxYq1xN9uXGs2ukIyAxChClDDUbWsOw3YZgBW8FklLNqRJgPjKW995AysjUBcRm+S5TDg=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-release
  - env: EMBER_TRY_SCENARIO=ember-beta
  - env: EMBER_TRY_SCENARIO=ember-canary
  - node_js: 'stable'

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- npm config set spin false
- npm install -g coveralls pr-bumper

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- if [ $EMBER_TRY_SCENARIO == "default" ]; then $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh; fi

after_success:
- $(npm root -g)/pr-bumper/.travis/maybe-publish-coverage.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: WpK7AxnPk8tPgEEWqq7c6u9owwfvge5JwdWlvKxbBavCDfrOEkzxHytCXgsXi3svEMUPpvEfZgQB8d1dVIox9lHypKiDv0gspE3lyVcUhoWjTajJ63DhF6qtwxCugmEH3RnkePyPL4nNx1EwbEexDkL1Km2Kl1eoo7fRBq5SHd/NFXE3D9tcMK4DNmHKEM70w/X58zYIimG4sIE/jjTdHnayuJcKclc698eGP8770DzrFxPsdZS2Ki3qixvjw33MpyUIcVEHldRy9sooknMM1UH/0fnim4+yKugwedZ6Dfn2oiyPZ6jWXJSMWRKXaxLCaijba75eTu+CH27SJgm6LHRfK15V1CqXr2nbq1BEUIEJfbJ66RNSMeX12pyM8Zxecknx9wvEbZvoOt4a5ImV5ulDDQB5yUWmt7MS3d+WlHt6kqUw0SFnNXQyfyIMgsB1cqKFJLbXf+8VbvUUvhWQEkryLL4rzc4ukB0KzU+AuKsLxbThgX8lKbUyWpwrndPF9BOe8Tys8jjlLz0WMc4BeADWOLuU2pXa6y3tbf21i51o3fh9SweBQZclyIr6aGJPaphRjubXc4gKYZ0P1wdQFXAJhqyAJafvdhQYBzMlnUI3tXiJrV2i37opMg/ApAn+t5zDki32GpzQZjSasYyrQU2GFaE6PEcbgD9sCSp/Qg0=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    node: 'stable'
    tags: true

after_deploy:
- .travis/publish-gh-pages.sh

notifications:
  slack:
    secure: 4drw+3XcsDo570yvpiccircR3Lrc+aGosLihbREmUvHNsyaTBv9GJimD7d4nSo0LbGy0jkTWdBHtoLijVy2xakY/8OpaXaeC8WWv1X0Gjjl0rd/lbpWqTYL8bRqOKs429vUsVEVtVBzIEMWMINamEuGVuYGOmCwxG22jh0wgN8R3k2Iu8rDMl/p6jI7MVxRs5/rOf5TIHKeozMTRZdsm45dImVfPHIazwCgzklFCRjJTRq937av4AU0KvIznCd1DbqgUY6CpeeIwzqbXJ+ePtA3K2NEjBaYgt3dpqD8CjuVsktSchRVAW0TCyCSiEUgmNmtyGa00tmJ70FkPOs62YxlWJEw8ujTTe+nJTooN7PCZLUjv4ZpDRSiriY50ARtXmGvbzs9BUu0afhKJCM1ihL6xlQ/qW+WWkn4qiRKcQ6JXAMGBzBvbzE9t6iH9hGadh9pwMpFJHquZdbV83J/39jQjoSa1oRMmyVjKFrlPNKXWYL/OXobMZoSSznQZ3aeXSgGK8SUrf3Ni4dQTBTftSgd6uaE77L1St1yaZI+gGLkjpcVaNdyKlQPBk26gUBkUuv9pbZ1545JHJg76/9/thAJNOrPKLsfQGkix+sGw8j3HT3nNloE4tp8Rxf7UNdYcpZe8BCX2V5G/CUIe2Fc4PnHfzNoeMUC1spL2h76b7uw=
